import { Grid } from "@mui/material";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CreateTransaction from "./components/transaction/actions/CreateTransaction";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isLoggedIn = false;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Grid container spacing={2}>
          <Grid item xs={3}></Grid>
          <Grid item xs={6}>
            <h1>Transactions</h1>
            {children}
          </Grid>
          <Grid item xs={3}>
            <CreateTransaction />
          </Grid>
        </Grid>
      </body>
    </html>
  );
}
